"""Provider-neutral request and response types.

The agent code talks only to these types, never to a vendor SDK. That is not
abstraction for its own sake: the tiering ablation has to run the same agent
against different models to say anything about cost, and the offline test suite
has to run it against no model at all.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class Role(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


@dataclass(frozen=True, slots=True)
class ToolSpec:
    """A tool as advertised to the model."""

    name: str
    description: str
    parameters: dict[str, Any]


@dataclass(frozen=True, slots=True)
class ToolCall:
    """A tool invocation the model asked for.

    ``call_id`` is generated by us rather than taken from the provider, because
    it is the anchor the evidence chain cites and it has to be stable across a
    cache replay on a different provider.
    """

    call_id: str
    name: str
    arguments: dict[str, Any]


@dataclass(frozen=True, slots=True)
class Message:
    role: Role
    content: str = ""
    tool_calls: tuple[ToolCall, ...] = ()
    tool_call_id: str | None = None
    tool_name: str | None = None


@dataclass(frozen=True, slots=True)
class Usage:
    input_tokens: int = 0
    output_tokens: int = 0
    thinking_tokens: int = 0

    @property
    def total(self) -> int:
        return self.input_tokens + self.output_tokens + self.thinking_tokens

    def __add__(self, other: Usage) -> Usage:
        return Usage(
            self.input_tokens + other.input_tokens,
            self.output_tokens + other.output_tokens,
            self.thinking_tokens + other.thinking_tokens,
        )


@dataclass(frozen=True, slots=True)
class LlmResponse:
    text: str
    tool_calls: tuple[ToolCall, ...] = ()
    usage: Usage = field(default_factory=Usage)
    model: str = ""
    from_cache: bool = False
    latency_seconds: float = 0.0

    @property
    def wants_tool(self) -> bool:
        return bool(self.tool_calls)


@dataclass(frozen=True, slots=True)
class GenerationConfig:
    """Request knobs that must participate in the cache key.

    Anything here that changes the model's output has to be part of the key, or
    a cached response from a different configuration would be replayed as if it
    answered the current question.
    """

    max_output_tokens: int = 800
    temperature: float = 0.0
    json_schema: dict[str, Any] | None = None


class QuotaExhaustedError(RuntimeError):
    """Raised when every shard is rate limited and the caller must back off."""


class ProviderError(RuntimeError):
    """A provider returned an error we cannot retry our way out of."""
